defaults:
  - hydra: default
  - datamodule: av2
  - model: model_multiagent

seed: 2333
monitor: val_AvgMinFDE
save_top_k: 1

data_root: /home/jerome.zhou/data/av2
checkpoint: 
output: qcnet_simpl/spa_6_propose_1_refine_1_scene_1_0.0002_4/use_N_change_mask_block_no_src
# trainer
num_workers: 128
gpus: [0,1,2,3]
sync_bn: true
batch_size: 4
epochs: 60
warmup_epochs: 10
post_norm: False
road_embed_type: transform
tempo_embed_type: norm

# optimizer
lr: 0.00015
weight_decay: 1e-4
gradient_clip_val: 
gradient_clip_algorithm: 

limit_train_batches:
limit_val_batches:
limit_test_batches:
log_model: all
test: false

wandb: disable