defaults:
  - hydra: default
  - datamodule: av2
  - model: model_forecast

seed: 2333
monitor: val_loss
save_top_k: 10

data_root:
checkpoint:
pretrained_weights:
output: ${model.name}-${model.phase}

# trainer
num_workers: 8
gpus: 1
sync_bn: true
batch_size: 32
epochs: 60
warmup_epochs: 10
post_norm: False
road_embed_type: transform
tempo_embed_type: T5

# optimizer
lr: 0.0002
weight_decay: 1e-4
gradient_clip_val: 
gradient_clip_algorithm: 

limit_train_batches:
limit_val_batches:
limit_test_batches:
log_model: all
test: false

wandb: disable