name: multiagent-baseline
phase: baseline

target:
  _target_: src.model.multiagent.trainer_multiagent.Trainer
  dim: 128
  historical_steps: 50
  future_steps: 60
  embedding_type: "fourier"
  encoder_depth: 3
  spa_depth: 6
  decoder_depth: 6
  scene_score_depth: 1
  num_heads: 8
  attn_bias: True
  ffn_bias: True
  dropout: 0.1
  num_modes: 6
  act_layer: nn.GELU
  norm_layer: nn.LayerNorm
  lr: ${lr}
  weight_decay: ${weight_decay}
  epochs: ${epochs}
  warmup_epochs: ${warmup_epochs}
