_target_: src.datamodule.av2_datamodule.Av2DataModule

data_root: ${data_root}
data_folder: multiagent-baseline-norm-200-all-time-lane
train_batch_size: ${batch_size}
val_batch_size: ${batch_size}
test_batch_size: ${batch_size}
shuffle: True
num_workers: ${num_workers}
pin_memory: True
